language: ruby
rvm:
  - 2.5.1

env:
  global:
    - secure: "NTHxW02t2VQYAcg72SDrrgqIPqzPDOyZr/HKZaRVxrMqWjp0NmDBMg7QieG8bIibGYxCnf/MhuIj40Id7RlhZLmOG2ttFmCPlCFZSjDeTrIxmK0N1T1xO1rMmXyJcOQIhQqERfraqYbpzI24q68qXjYM0mSKzKCQgzBT8uKYuvQ=" # GITHUB_TOKEN

before_script:
  - chmod +x ./script/cibuild
  - chmod +x ./script/deploy-pages

script:
  ./script/cibuild

branches:
  only: jekyll

after_success:
  - ./script/deploy-pages

sudo: false
