# Site settings
name: Maxime Colmant's website
description: Personal website of Maxime Colmant
url: http://mcolmant.github.io
last_update: 01/2017

# Build settings
markdown: kramdown
gems: ['jekyll/scholar', 'jekyll-sitemap']

scholar:
  style: ieee.csl
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: bibliography.bib
  bibliography_template: entry-bib

exclude: ['Rakefile', 'README.md', "*.sublime-project", "*.sublime-workspace", ".DS_Store"]
