# Site settings
name: Maxime Colmant's website
description: Personal website of Maxime Colmant
url: http://mcolmant.github.io
last_update: 04/2017

# Build settings
markdown: kramdown
gems: ['jekyll/scholar', 'jekyll-sitemap']

scholar:
  style: ieee.csl
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: bibliography.bib
  bibliography_template: entry-bib

acceptance_rates:
  'colmant:hal-01130030': '32/150 (~21%)'
  'colmant:hal-01439889': '64/280 (~23%)'
  'havet:hal-01403486': '14/58 (~24%)'

exclude: ['Gemfile*', 'README.md', "*.sublime-project", "*.sublime-workspace", ".DS_Store", "script"]
